---
apiVersion: v1
kind: Config
clusters:
- name: "dev-ip-172-31-37-33"
  cluster:
    server: "https://172.31.37.33:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl6TURFeU56RXdNRFUxTVZvWERUTXpNREV5TkRFd01EVTFNVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUxsamE2alBsZExVCkRiUEFobkhkOUFOL3ZKbTZYVE95a1ovcTY5M05HSlYrN3Z2UDlRdHF3T\
      G1MWTBDY2tTOWJVUnBaaW5EaUdHV1UKNWZJaFBjZjRUNklEUEFURFN4NnZncHhmNXNMeHZvei80b\
      WR5TE1oaUUyc3pvMUpJSDNUSzlpUk1ubzJTR2E5RgpZbS9Ha01ab3UrYXFkMlFtR0hwcEdmQkxDN\
      kswU1VpcXRxQ0dmNVdPNGJaK2F0R3ZQVG9na2NGNFZ3MTUyYUU4Ck5VSnRMRW1TTlA3SHM3UkpaT\
      zF5YU1JVExpbkpxcUtzZytDN1F3RXZmdFcyQjR2WDE5bFVFa1V1UjNBclRjL1AKUmQ3dVloMmtEU\
      i92UXhiTzVKTmZEWkxsL2d4SE5vcFlqSmZCajZBSjAyT2hHbnFCRWZwanRIY0tmeERjWWZEcgpuU\
      U1xVHh0STVFMENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGQmkxSys1TlN6ZFpFUnhXay8wcEZmaWY4K3N0TUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQWVoMU16eG1rVm0zMjc5VzJvNUJxT1lwekZiR0tJSVpKN2Y2V\
      mhNTmZBUFo0bjhvWEt1VThwa1BDUwpsa0JRelFZOUU4QUtqYmI2eEtKRU13emx6NGdOQ01JTFVVR\
      0lTZEY0K3FXcUdrbXZNQ1Z1OXE0OEM0cUxBdEZ3Cjg3QVl1dFBOVTZWdTFXWjlrMmtqR1VoUkFvc\
      3dya3J2ckk4Y2dMbUhWZEVzdVFZUW9Yb2FYRGpyV2dCRzllek0KTys5cUZ2S3loUDdHYWtCb0Q1Q\
      TMzMGxYanNsamw4dm80U2pTNG5UMmRrN1BKcW1vdytsMExMMDBOWW5pZjdWTApYTGN4TFF4U0VVM\
      VVZK2s5azRTVWlNRTlkb2RFQm5pa3dJRzFTdEJjN3dIdkQxazJJcXlhcVBrTE5ZZ2tlZmlICmJPb\
      0FybmJmSVd1VDlQK3grVVRyL1k2dHIyelUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "dev"
  user:
    token: "kubeconfig-user-v48gxdrkbn:hn5wvxr4q4v2zvnzlr2n7922n4p2ld5qrscg7qmx2vjd56x8pjv772"


contexts:
- name: "dev-ip-172-31-37-33"
  context:
    user: "dev"
    cluster: "dev-ip-172-31-37-33"

current-context: "dev-ip-172-31-37-33"

---
apiVersion: v1
kind: Config
clusters:
- name: "infra"
  cluster:
    server: "https://rancher.devopsforlife.io/k8s/clusters/c-wt4qx"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2akNDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      FkzTkRneApNVE0yTkRBZUZ3MHlNekF4TWpjd09USXlORFJhRncwek16QXhNalF3T1RJeU5EUmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qYzBPREV4TXpZME1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRS9MN0xTY083WS9vRApscDZhaUNpVU1HRVBhQ2hacjBNL0pLSWV0W\
      lZVMVlDWWJYb3dBU2pNZEVvMk1BUnBlb1E2UXp0WjIrYUdjVXpXCkh0Tkl3MWtPRHFOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      0pwTXAxRm43VDkxODhPZnBvQ0xZOUsrWDQvTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFEMAp1T\
      ngzbkNFNFNqTy9DSlo4eEtlbE8zR3ZIcjUxaGRlbU5YRjhScklHS1FJaEFNQ2R6dUtYU1laZkZle\
      ThGWlQxCms5ditvbDd0dUpzbmRpa1IvdjRWd1E0bwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
- name: "infra-ip-172-31-40-12"
  cluster:
    server: "https://172.31.40.12:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl6TURFeU56RXdNRE0wTTFvWERUTXpNREV5TkRFd01ETTBNMW93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU9JTlA0UEVncVplCnZBZ040aC85dVhRM0JDd2g0RzRoVGFZNnNLK2NMNWI3QkUrQ1lGeklkV\
      Vl3Y2JPbGRrRHp3L1VpSnpmdVhnMTcKN3B6Y25PUG91TlU3YVFndS9qRk1ub2V4Rm94VEZ3Q2Zod\
      Cs3dFhZOGFaV1QrcThVZVJzcHJjbWFZWktiaTZNNwplMFRTVHhaYzZIajBqWnJxcmU3L05CVy9la\
      zVaTzdtc0NvSkpDODBiWWxYN0RrblQvaGFpb3ZRcDBaR3NjRldNCmZ2YW1uSVFRUXBuL3kweEZZb\
      m8wU21lejJZTys4VzdoaWxnbmhJbkMwYWNMbzNobDdaUkMxN3FsY0VVb1RoV3EKeEE3MUpMV2tvY\
      lA5OWFRdC8yNW1ZZnhLME5uSWR4cXg5SkZRVGxmSUp2QUM1Z1hKMWNBUTJNNTBlQmxOWEtKNQpoT\
      nJzKzNQdzFWa0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGQXNoZnlSL2dleUlrU0FmTWRsWGZUSlhlbVJyTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQUZ3UjdLMFFIRzNWOXd2eEMzRkFFVDlOLzJYRVBqNjFDcnFsO\
      VhnWTdxanB1UXp3Q3pjUDlVYWVOMQpYRUhGeUZwNXhmTlVYMStBdjF2NTJaVndxSjkyQjljN0FDb\
      TNBOHZuSXFpVzRvTG85MTRoVVZkUzBZSlU1eGFaCjBxd0VWS2REVENmNFlycTdIQjUxVE5aY2psS\
      U1ZaVVJc0RaQmRMYitiMFNRS1hZNFRXN3hCekdpR1lMb0h6V2gKSTA4OHZLa2NsRFdlWU96K2dTY\
      XJBN2dRSitITWtXQnluUzhUSXBwTXBTRUdLNjdzOGNRQ29MUUlIQll0eDQ3RAp0YlFkOUI5NlcwZ\
      29GamFVb3RXcm96dCtFbFpXNjI3dFB3aU1NSG5PZkh2NVlGREl1dm5ZdzJabUUvZTlMWjVxCmVDb\
      TFIYjZ5M1JPVFFpdFlUeXpXb0dEc1kvbHgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "infra"
  user:
    token: "kubeconfig-user-v48gxht54z:btf4957vr4pmflpmq4wxb5b4k6c2wkbfsghtl8r25hfv8zfkng9fqp"


contexts:
- name: "infra"
  context:
    user: "infra"
    cluster: "infra"
- name: "infra-ip-172-31-40-12"
  context:
    user: "infra"
    cluster: "infra-ip-172-31-40-12"

current-context: "infra"


